# Generated by Django 5.2.17 on 2026-09-13 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('actor', models.CharField(default='System', max_length=100)),
                ('target', models.CharField(blank=True, default='', max_length=150)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('camera_required', models.BooleanField(default=True)),
                ('id_verification_required', models.BooleanField(default=True)),
                ('rules', models.TextField(default='1. Strict Fullscreen mode is mandatory.\n2. Do not switch browser tabs or windows.\n3. Keep camera preview active.\n4. Detectable security violations will pause or terminate session.\n5. Single vote per eligible voter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(default='III', max_length=10)),
                ('section', models.CharField(default='A', max_length=10)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('manifesto', models.TextField(blank=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='votechain_backend.election')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousVotingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_tokens', to='votechain_backend.election')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('STUDENT', 'Student Voter')], default='STUDENT', max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(default='Information Technology', max_length=100)),
                ('year', models.CharField(default='III', max_length=10)),
                ('section', models.CharField(default='A', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible')], default='ELIGIBLE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('verification_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20)),
                ('temporary_password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FULLSCREEN_EXIT', 'Fullscreen Exited'), ('TAB_SWITCH', 'Tab Switched / Hidden'), ('WINDOW_FOCUS_LOST', 'Window Focus Lost'), ('CAMERA_PERMISSION_DENIED', 'Camera Permission Denied'), ('CAMERA_STREAM_STOPPED', 'Camera Stream Interrupted'), ('SESSION_TIMEOUT', 'Session Timeout'), ('MULTIPLE_LOGIN', 'Multiple Simultaneous Logins'), ('INVALID_TOKEN', 'Invalid Anonymous Token'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Resource Access'), ('DUPLICATE_VOTE_ATTEMPT', 'Duplicate Vote Attempt Blocked')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('details', models.TextField()),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='votechain_backend.election')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='votechain_backend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IDVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_image', models.TextField(blank=True, null=True)),
                ('document_hash', models.CharField(blank=True, max_length=64)),
                ('extracted_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('match_score', models.FloatField(default=100.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_verifications', to='votechain_backend.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VoterEligibilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('voting_session_token', models.CharField(blank=True, max_length=100, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_records', to='votechain_backend.election')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_records', to='votechain_backend.userprofile')),
            ],
            options={
                'unique_together': {('student', 'election')},
            },
        ),
    ]
