# Generated by Django 5.1.15 on 2026-09-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votechain_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='department',
            field=models.CharField(default='ALL', max_length=100),
        ),
    ]
