# Generated by Django 5.1.15 on 2026-09-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votechain_backend', '0002_election_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CEO', 'Chief Election Officer'), ('ADMIN', 'System Administrator'), ('STUDENT', 'Student Voter')], default='STUDENT', max_length=20),
        ),
    ]
