# Generated by Django 5.2.17 on 2026-09-18 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votechain_backend', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_entity', models.CharField(blank=True, max_length=150)),
                ('actor_hash', models.CharField(default='SYSTEM', max_length=64)),
                ('details', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('audit_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hardware_key_credential_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hardware_key_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip_whitelist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='rules',
            field=models.TextField(default='1. Controlled session required.\n2. Biometric and camera monitoring active.\n3. Ephemeral key ballot encryption.\n4. Single vote per verified voter.'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('FULLSCREEN_EXIT', 'Fullscreen Exited'), ('TAB_SWITCH', 'Tab Switched / Hidden'), ('WINDOW_FOCUS_LOST', 'Window Focus Lost'), ('CAMERA_PERMISSION_DENIED', 'Camera Permission Denied'), ('CAMERA_STREAM_STOPPED', 'Camera Stream Interrupted'), ('SESSION_TIMEOUT', 'Session Timeout'), ('MULTIPLE_LOGIN', 'Multiple Simultaneous Logins'), ('INVALID_TOKEN', 'Invalid Anonymous Token'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Resource Access'), ('DUPLICATE_VOTE_ATTEMPT', 'Duplicate Vote Attempt Blocked'), ('BRUTE_FORCE_ATTEMPT', 'Brute Force Authentication Spike'), ('CRYPTO_VERIFICATION_FAIL', 'Cryptographic Verification Failure')], max_length=50),
        ),
        migrations.CreateModel(
            name='EncryptedVoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_vote_payload', models.TextField()),
                ('vote_hash', models.CharField(db_index=True, max_length=64)),
                ('nullifier_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('zk_proof_ref', models.CharField(blank=True, max_length=128)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('audit_block_id', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_votes', to='votechain_backend.election')),
            ],
        ),
    ]
