# Generated by Django 5.2.17 on 2026-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votechain_backend', '0004_voteaudittrail_userprofile_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CEO', 'Chief Election Officer'), ('ADMIN', 'System Administrator'), ('STUDENT', 'Student Voter'), ('EVM', 'EVM Kiosk Station')], default='STUDENT', max_length=20),
        ),
    ]
