# Generated by Django 5.2.17 on 2026-09-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votechain_backend', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election_symbol',
            field=models.CharField(default='★', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='President', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='priorities',
            field=models.TextField(blank=True, default='• Student Activities\n• Technical Events\n• Sports & Culture\n• Campus Facilities\n• Academic Mentorship'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='symbol_name',
            field=models.CharField(default='Star', max_length=100),
        ),
        migrations.AddField(
            model_name='election',
            name='academic_year',
            field=models.CharField(default='2026', max_length=20),
        ),
        migrations.AddField(
            model_name='election',
            name='eligible_departments',
            field=models.CharField(default='ALL', max_length=200),
        ),
        migrations.AddField(
            model_name='election',
            name='eligible_years',
            field=models.CharField(default='ALL', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card_qr_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('COUNTING', 'Counting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student Voter'), ('EVM', 'EVM Officer'), ('ADMIN', 'System Administrator'), ('CEO', 'Chief Election Officer')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(default='INFO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='votechain_backend.userprofile')),
            ],
        ),
    ]
