# Generated by Django 5.2.17 on 2026-09-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votechain_backend', '0006_candidate_biography_candidate_election_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusNetworkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid_name', models.CharField(default='COLLEGE_WIFI', max_length=100)),
                ('allowed_cidrs', models.TextField(default='127.0.0.1/32\n10.0.0.0/8\n172.16.0.0/12\n192.168.0.0/16\n::1/128')),
                ('enforcement_mode', models.CharField(choices=[('STRICT', 'Strict Production Campus Access'), ('DEVELOPMENT', 'Development Mode (Local Network Allowed)')], default='DEVELOPMENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('election_access_required', models.BooleanField(default=True)),
                ('voting_start_time', models.CharField(default='09:00', max_length=10)),
                ('voting_end_time', models.CharField(default='16:00', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(default='IT Department', max_length=100)),
                ('location', models.CharField(default='Voting Lab 1', max_length=150)),
                ('role_target', models.CharField(choices=[('EVM', 'EVM Voting Kiosk'), ('ADMIN', 'Admin Terminal'), ('STUDENT_KIOSK', 'Student Campus Kiosk'), ('ALL', 'General Device')], default='EVM', max_length=20)),
                ('status', models.CharField(choices=[('TRUSTED', 'Trusted'), ('PENDING', 'Pending Approval'), ('BLOCKED', 'Blocked / Revoked'), ('EXPIRED', 'Expired')], default='TRUSTED', max_length=20)),
                ('last_verified_ip', models.CharField(default='127.0.0.1', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('FULLSCREEN_EXIT', 'Fullscreen Exited'), ('TAB_SWITCH', 'Tab Switched / Hidden'), ('WINDOW_FOCUS_LOST', 'Window Focus Lost'), ('CAMERA_PERMISSION_DENIED', 'Camera Permission Denied'), ('CAMERA_STREAM_STOPPED', 'Camera Stream Interrupted'), ('SESSION_TIMEOUT', 'Session Timeout'), ('MULTIPLE_LOGIN', 'Multiple Simultaneous Logins'), ('INVALID_TOKEN', 'Invalid Anonymous Token'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Resource Access'), ('DUPLICATE_VOTE_ATTEMPT', 'Duplicate Vote Attempt Blocked'), ('BRUTE_FORCE_ATTEMPT', 'Brute Force Authentication Spike'), ('CRYPTO_VERIFICATION_FAIL', 'Cryptographic Verification Failure'), ('UNAUTHORIZED_NETWORK', 'Unauthorized External Network Attempt'), ('UNKNOWN_DEVICE', 'Unknown / Unregistered Device Blocked'), ('BLOCKED_DEVICE', 'Revoked / Blocked Device Attempt'), ('ACCESS_GRANTED', 'Campus Gateway Access Granted'), ('ACCESS_DENIED', 'Campus Gateway Access Denied'), ('DEVICE_REGISTERED', 'New Trusted Device Registered'), ('DEVICE_REVOKED', 'Trusted Device Access Revoked'), ('SESSION_STARTED', 'Campus Secure Session Started'), ('SESSION_TERMINATED', 'Campus Secure Session Terminated')], max_length=50),
        ),
    ]
