# Generated by Django 5.2.17 on 2026-09-19 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votechain_backend', '0007_campusnetworkpolicy_deviceregistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='daily_end_time',
            field=models.CharField(default='16:00', max_length=10),
        ),
        migrations.AddField(
            model_name='election',
            name='daily_start_time',
            field=models.CharField(default='09:00', max_length=10),
        ),
        migrations.AddField(
            model_name='election',
            name='voting_hours_enforced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encryptedvoterecord',
            name='kiosk_device_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='encryptedvoterecord',
            name='vote_source',
            field=models.CharField(default='STUDENT_PORTAL', max_length=30),
        ),
        migrations.CreateModel(
            name='ElectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('certificate_type', models.CharField(choices=[('WINNER', 'Certificate of Victory & Student Leadership Distinction'), ('CANDIDATE', 'Certificate of Democratic Candidacy & Honor'), ('VOTER', 'Certificate of Democratic Participation & Civic Responsibility')], max_length=20)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_id', models.CharField(max_length=50)),
                ('department', models.CharField(default='ALL', max_length=100)),
                ('academic_year', models.CharField(default='2026', max_length=20)),
                ('position_title', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.CharField(blank=True, default='★', max_length=50)),
                ('symbol_name', models.CharField(blank=True, default='Star', max_length=100)),
                ('votes_received', models.IntegerField(default=0)),
                ('total_votes_cast', models.IntegerField(default=0)),
                ('vote_percentage', models.FloatField(default=0.0)),
                ('margin', models.IntegerField(default=0)),
                ('block_index', models.IntegerField(default=1)),
                ('block_hash', models.CharField(blank=True, default='', max_length=64)),
                ('tx_id_ref', models.CharField(blank=True, default='', max_length=64)),
                ('certificate_hash', models.CharField(db_index=True, max_length=64)),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_certified', models.BooleanField(default=True)),
                ('institution_seal', models.CharField(default='ABC INSTITUTION - STUDENTVOICEX RETURNING BOARD', max_length=150)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='votechain_backend.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='votechain_backend.election')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='votechain_backend.userprofile')),
            ],
        ),
    ]
